src/Entity/User.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints as Assert;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface , PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Type('string')]
    #[Assert\Length(
        min: 2,
        max: 10,
        minMessage: 'Your first name must be at least {{ limit }} characters long',
        maxMessage: 'Your first name cannot be longer than {{ limit }} characters',
    )]
    #[Assert\Regex(
        pattern: '/\d/',
        match: false,
        message: 'Your name cannot contain a number',
    )]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Type('string')]
    #[Assert\Length(
        min: 2,
        max: 10,
        minMessage: 'Your first name must be at least {{ limit }} characters long',
        maxMessage: 'Your first name cannot be longer than {{ limit }} characters',
    )]
    #[Assert\Regex(
        pattern: '/\d/',
        match: false,
        message: 'Your name cannot contain a number',
    )]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
   // #[Assert\NotBlank]
    #[Assert\Type('string')]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]

    /**
     * @var string The hashed password
     */
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $role = null;

    #[ORM\Column(length: 255)]
    #[Assert\Email(
        message: 'The email {{ value }} is not a valid email.',
    )]
    private ?string $mail = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?bool $enabled = true;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ArticleArtiste::class, orphanRemoval: true)]
    private Collection $articleArtistes;

    public function __construct()
    {
        $this->articleArtistes = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }
    public function getRoles()
    {
        return ['ROLE_USER'];
    }
    public function getUserIdentifier(): string
    {
        // TODO: Implement getUserIdentifier() method.
        return (string) $this->username;
    }

    public function isEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * @return Collection<int, ArticleArtiste>
     */
    public function getArticleArtistes(): Collection
    {
        return $this->articleArtistes;
    }

    public function addArticleArtiste(ArticleArtiste $articleArtiste): self
    {
        if (!$this->articleArtistes->contains($articleArtiste)) {
            $this->articleArtistes->add($articleArtiste);
            $articleArtiste->setUser($this);
        }

        return $this;
    }

    public function removeArticleArtiste(ArticleArtiste $articleArtiste): self
    {
        if ($this->articleArtistes->removeElement($articleArtiste)) {
            // set the owning side to null (unless already changed)
            if ($articleArtiste->getUser() === $this) {
                $articleArtiste->setUser(null);
            }
        }

        return $this;
    }
    public function getFulName():string{
        return $this->getNom().' '.$this->getPrenom();
    }

}

templates/pages/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<input type="submit" value="{{ submitButtonText ?? 'Ajouter Article' }}" class="btn btn-primary btn-block " formnovalidate>
{{ form_end(form) }}

templates/pages/create.html.twig
{% extends 'layouts/base.html.twig' %}
{% block title 'Créer un Article ' %}
{% block body %}
<div class="row">
    <div class="col-md-6 mx-auto">
        <h1>Création Article</h1>

        {{ include('pages/_form.html.twig') }}
    </div>
</div>

{% endblock %}

templates/pages/home.html.twig

{% extends 'layouts/base.html.twig' %}

{% block body %}
    {% if arts|length >0 %}
<h1> Tunisia  &hearts;</h1>
<p>It's currently {{ 'now'|date('h:i A','Africa/Tunis') }}</p>

<h1 class="mt-4 mb-5 text-center text-muted">{{ pluralize(arts|length,'Article')}} </h1>

<body   id="myTable">

        {% for row in arts|batch(3) %}

            <div class="row mb-5">

                {% for i in row %}
                    <div class="col-md-4">
                        <table id="t">
                        <Article class="article bg-white rounded shadow" >
                         <div class="mw-100 overflow-hidden">
                            <a href="{{ path('app_articles_show',{idArticle: i.idArticle}) }}">
                                <div class="animation-transition-slow">
                                    <img  src="{{ (i.imageH ? vich_uploader_asset(i) :asset('images/download.jpg')) | imagine_filter('squared_thumbnail_medium') }}" alt="{{ i.nomA }}" class="w-100 rounded-top  "/>

                                </div>


                            </a>

                            <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_articles_show',{idArticle: i.idArticle}) }}" class="text-secondary text-decoration-none">{{ i.nomA }}</a></h2>

                            <p class="pl-3 pb-3 text-muted"> <small>Créer par {{ i.user.fulName}}</small></p>
                         </div>
                        </Article>
                        </table>
                    </div>
                {% endfor %}
             </div>
        {% endfor %}
        {% else %}
<p class=" mt-5 h1  text-center">Pas encore d'articles. <a href="{{ path('app_articles_create') }}" >Soyez le premier!</a></p>
{% endif %}

</body>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

{% endblock %}


templates/pages/modifier.html.twig
{% extends 'layouts/base.html.twig' %}
{% block title 'Modifier Article '~ article.idArticle %}
{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
             <h1>Modifier Article {{ article.idArticle }}</h1>
            {{ include('pages/_form.html.twig',{submitButtonText:'Modifier Article '} ) }}
        </div>
    </div>
{% endblock %}

templates/pages/show.html.twig


{% extends 'layouts/base.html.twig' %}
{% block body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <Article class="article bg-white rounded shadow" >
               <div class="mw-100 rounded-top overflow-hidden">
                <img src="{{ (article.imageH ? vich_uploader_asset(article) :asset('images/download.jpg')) | imagine_filter('squared_thumbnail_medium') }}" alt="{{ article.nomA }}" class="w-100 rounded-top"/>
               </div>

                <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_articles_show',{idArticle: article.idArticle}) }}" class="text-secondary text-decoration-none">{{ article.nomA }}</a></h2>
                <p class="pl-3 pb-3 text-muted"> <small>Soumis {{ article.createdAt|ago }} par {{ article.user.fulName}}</small></p>
                <p class="pl-3 pb-3 pr-3 text-break">{{ article.descriptionA }}</p>

                <div class="pl-3  pb-3" >
                    <a href=" {{ path('app_articles_modif',{idArticle: article.idArticle}) }} " class="btn btn-light">Modifier</a>

                    <a href="#" onclick="event.preventDefault();confirm('Êtes-vous sûr de vouloir supprimer?')&& document.getElementById('js-article-supprimer-form').submit();"  class="btn btn-light">Supprimer</a>

                    <form id="js-article-supprimer-form" action="{{ path('app_articles_supp',{idArticle: article.idArticle}) }}" method="post" style="display: none;">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token('article_suppression_'~ article.idArticle) }}">
                        <input type="hidden" name="_method" value="DELETE">
                    </form>
                </div>
            </Article>


        </div>
    </div>

{% endblock %}